//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClientApplication.AdminService1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AdminServiceSoap", Namespace="http://tempuri.org/")]
    public partial class AdminService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getAlunosLOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCadeirasLOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCadeirasAlunoLOperationCompleted;
        
        private System.Threading.SendOrPostCallback addAlunoLOperationCompleted;
        
        private System.Threading.SendOrPostCallback addCadeiraLOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAlunosMOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCadeirasMOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCadeirasAlunoMOperationCompleted;
        
        private System.Threading.SendOrPostCallback addAlunoMOperationCompleted;
        
        private System.Threading.SendOrPostCallback addCadeiraMOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAlunosDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCadeirasDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCadeirasAlunoDOperationCompleted;
        
        private System.Threading.SendOrPostCallback addAlunoDOperationCompleted;
        
        private System.Threading.SendOrPostCallback addCadeiraDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AdminService() {
            this.Url = global::ClientApplication.Properties.Settings.Default.ClientApplication_AdminService1_AdminService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getAlunosLCompletedEventHandler getAlunosLCompleted;
        
        /// <remarks/>
        public event getCadeirasLCompletedEventHandler getCadeirasLCompleted;
        
        /// <remarks/>
        public event getCadeirasAlunoLCompletedEventHandler getCadeirasAlunoLCompleted;
        
        /// <remarks/>
        public event addAlunoLCompletedEventHandler addAlunoLCompleted;
        
        /// <remarks/>
        public event addCadeiraLCompletedEventHandler addCadeiraLCompleted;
        
        /// <remarks/>
        public event getAlunosMCompletedEventHandler getAlunosMCompleted;
        
        /// <remarks/>
        public event getCadeirasMCompletedEventHandler getCadeirasMCompleted;
        
        /// <remarks/>
        public event getCadeirasAlunoMCompletedEventHandler getCadeirasAlunoMCompleted;
        
        /// <remarks/>
        public event addAlunoMCompletedEventHandler addAlunoMCompleted;
        
        /// <remarks/>
        public event addCadeiraMCompletedEventHandler addCadeiraMCompleted;
        
        /// <remarks/>
        public event getAlunosDCompletedEventHandler getAlunosDCompleted;
        
        /// <remarks/>
        public event getCadeirasDCompletedEventHandler getCadeirasDCompleted;
        
        /// <remarks/>
        public event getCadeirasAlunoDCompletedEventHandler getCadeirasAlunoDCompleted;
        
        /// <remarks/>
        public event addAlunoDCompletedEventHandler addAlunoDCompleted;
        
        /// <remarks/>
        public event addCadeiraDCompletedEventHandler addCadeiraDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAlunosL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Main[] getAlunosL() {
            object[] results = this.Invoke("getAlunosL", new object[0]);
            return ((Main[])(results[0]));
        }
        
        /// <remarks/>
        public void getAlunosLAsync() {
            this.getAlunosLAsync(null);
        }
        
        /// <remarks/>
        public void getAlunosLAsync(object userState) {
            if ((this.getAlunosLOperationCompleted == null)) {
                this.getAlunosLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAlunosLOperationCompleted);
            }
            this.InvokeAsync("getAlunosL", new object[0], this.getAlunosLOperationCompleted, userState);
        }
        
        private void OngetAlunosLOperationCompleted(object arg) {
            if ((this.getAlunosLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAlunosLCompleted(this, new getAlunosLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCadeirasL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cadeira[] getCadeirasL() {
            object[] results = this.Invoke("getCadeirasL", new object[0]);
            return ((Cadeira[])(results[0]));
        }
        
        /// <remarks/>
        public void getCadeirasLAsync() {
            this.getCadeirasLAsync(null);
        }
        
        /// <remarks/>
        public void getCadeirasLAsync(object userState) {
            if ((this.getCadeirasLOperationCompleted == null)) {
                this.getCadeirasLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCadeirasLOperationCompleted);
            }
            this.InvokeAsync("getCadeirasL", new object[0], this.getCadeirasLOperationCompleted, userState);
        }
        
        private void OngetCadeirasLOperationCompleted(object arg) {
            if ((this.getCadeirasLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCadeirasLCompleted(this, new getCadeirasLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCadeirasAlunoL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cadeira[] getCadeirasAlunoL(int numero) {
            object[] results = this.Invoke("getCadeirasAlunoL", new object[] {
                        numero});
            return ((Cadeira[])(results[0]));
        }
        
        /// <remarks/>
        public void getCadeirasAlunoLAsync(int numero) {
            this.getCadeirasAlunoLAsync(numero, null);
        }
        
        /// <remarks/>
        public void getCadeirasAlunoLAsync(int numero, object userState) {
            if ((this.getCadeirasAlunoLOperationCompleted == null)) {
                this.getCadeirasAlunoLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCadeirasAlunoLOperationCompleted);
            }
            this.InvokeAsync("getCadeirasAlunoL", new object[] {
                        numero}, this.getCadeirasAlunoLOperationCompleted, userState);
        }
        
        private void OngetCadeirasAlunoLOperationCompleted(object arg) {
            if ((this.getCadeirasAlunoLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCadeirasAlunoLCompleted(this, new getCadeirasAlunoLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addAlunoL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addAlunoL(string nome, int numero) {
            object[] results = this.Invoke("addAlunoL", new object[] {
                        nome,
                        numero});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addAlunoLAsync(string nome, int numero) {
            this.addAlunoLAsync(nome, numero, null);
        }
        
        /// <remarks/>
        public void addAlunoLAsync(string nome, int numero, object userState) {
            if ((this.addAlunoLOperationCompleted == null)) {
                this.addAlunoLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddAlunoLOperationCompleted);
            }
            this.InvokeAsync("addAlunoL", new object[] {
                        nome,
                        numero}, this.addAlunoLOperationCompleted, userState);
        }
        
        private void OnaddAlunoLOperationCompleted(object arg) {
            if ((this.addAlunoLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addAlunoLCompleted(this, new addAlunoLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addCadeiraL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addCadeiraL(string nomeCadeira, int numero, int notaFinal, int numCadeira) {
            object[] results = this.Invoke("addCadeiraL", new object[] {
                        nomeCadeira,
                        numero,
                        notaFinal,
                        numCadeira});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addCadeiraLAsync(string nomeCadeira, int numero, int notaFinal, int numCadeira) {
            this.addCadeiraLAsync(nomeCadeira, numero, notaFinal, numCadeira, null);
        }
        
        /// <remarks/>
        public void addCadeiraLAsync(string nomeCadeira, int numero, int notaFinal, int numCadeira, object userState) {
            if ((this.addCadeiraLOperationCompleted == null)) {
                this.addCadeiraLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddCadeiraLOperationCompleted);
            }
            this.InvokeAsync("addCadeiraL", new object[] {
                        nomeCadeira,
                        numero,
                        notaFinal,
                        numCadeira}, this.addCadeiraLOperationCompleted, userState);
        }
        
        private void OnaddCadeiraLOperationCompleted(object arg) {
            if ((this.addCadeiraLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addCadeiraLCompleted(this, new addCadeiraLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAlunosM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Main[] getAlunosM() {
            object[] results = this.Invoke("getAlunosM", new object[0]);
            return ((Main[])(results[0]));
        }
        
        /// <remarks/>
        public void getAlunosMAsync() {
            this.getAlunosMAsync(null);
        }
        
        /// <remarks/>
        public void getAlunosMAsync(object userState) {
            if ((this.getAlunosMOperationCompleted == null)) {
                this.getAlunosMOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAlunosMOperationCompleted);
            }
            this.InvokeAsync("getAlunosM", new object[0], this.getAlunosMOperationCompleted, userState);
        }
        
        private void OngetAlunosMOperationCompleted(object arg) {
            if ((this.getAlunosMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAlunosMCompleted(this, new getAlunosMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCadeirasM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cadeira[] getCadeirasM() {
            object[] results = this.Invoke("getCadeirasM", new object[0]);
            return ((Cadeira[])(results[0]));
        }
        
        /// <remarks/>
        public void getCadeirasMAsync() {
            this.getCadeirasMAsync(null);
        }
        
        /// <remarks/>
        public void getCadeirasMAsync(object userState) {
            if ((this.getCadeirasMOperationCompleted == null)) {
                this.getCadeirasMOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCadeirasMOperationCompleted);
            }
            this.InvokeAsync("getCadeirasM", new object[0], this.getCadeirasMOperationCompleted, userState);
        }
        
        private void OngetCadeirasMOperationCompleted(object arg) {
            if ((this.getCadeirasMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCadeirasMCompleted(this, new getCadeirasMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCadeirasAlunoM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cadeira[] getCadeirasAlunoM(int numero) {
            object[] results = this.Invoke("getCadeirasAlunoM", new object[] {
                        numero});
            return ((Cadeira[])(results[0]));
        }
        
        /// <remarks/>
        public void getCadeirasAlunoMAsync(int numero) {
            this.getCadeirasAlunoMAsync(numero, null);
        }
        
        /// <remarks/>
        public void getCadeirasAlunoMAsync(int numero, object userState) {
            if ((this.getCadeirasAlunoMOperationCompleted == null)) {
                this.getCadeirasAlunoMOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCadeirasAlunoMOperationCompleted);
            }
            this.InvokeAsync("getCadeirasAlunoM", new object[] {
                        numero}, this.getCadeirasAlunoMOperationCompleted, userState);
        }
        
        private void OngetCadeirasAlunoMOperationCompleted(object arg) {
            if ((this.getCadeirasAlunoMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCadeirasAlunoMCompleted(this, new getCadeirasAlunoMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addAlunoM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addAlunoM(string nome, int numero) {
            object[] results = this.Invoke("addAlunoM", new object[] {
                        nome,
                        numero});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addAlunoMAsync(string nome, int numero) {
            this.addAlunoMAsync(nome, numero, null);
        }
        
        /// <remarks/>
        public void addAlunoMAsync(string nome, int numero, object userState) {
            if ((this.addAlunoMOperationCompleted == null)) {
                this.addAlunoMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddAlunoMOperationCompleted);
            }
            this.InvokeAsync("addAlunoM", new object[] {
                        nome,
                        numero}, this.addAlunoMOperationCompleted, userState);
        }
        
        private void OnaddAlunoMOperationCompleted(object arg) {
            if ((this.addAlunoMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addAlunoMCompleted(this, new addAlunoMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addCadeiraM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addCadeiraM(string nomeCadeira, int numero, int notaFinal, int numCadeira) {
            object[] results = this.Invoke("addCadeiraM", new object[] {
                        nomeCadeira,
                        numero,
                        notaFinal,
                        numCadeira});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addCadeiraMAsync(string nomeCadeira, int numero, int notaFinal, int numCadeira) {
            this.addCadeiraMAsync(nomeCadeira, numero, notaFinal, numCadeira, null);
        }
        
        /// <remarks/>
        public void addCadeiraMAsync(string nomeCadeira, int numero, int notaFinal, int numCadeira, object userState) {
            if ((this.addCadeiraMOperationCompleted == null)) {
                this.addCadeiraMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddCadeiraMOperationCompleted);
            }
            this.InvokeAsync("addCadeiraM", new object[] {
                        nomeCadeira,
                        numero,
                        notaFinal,
                        numCadeira}, this.addCadeiraMOperationCompleted, userState);
        }
        
        private void OnaddCadeiraMOperationCompleted(object arg) {
            if ((this.addCadeiraMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addCadeiraMCompleted(this, new addCadeiraMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAlunosD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Main[] getAlunosD() {
            object[] results = this.Invoke("getAlunosD", new object[0]);
            return ((Main[])(results[0]));
        }
        
        /// <remarks/>
        public void getAlunosDAsync() {
            this.getAlunosDAsync(null);
        }
        
        /// <remarks/>
        public void getAlunosDAsync(object userState) {
            if ((this.getAlunosDOperationCompleted == null)) {
                this.getAlunosDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAlunosDOperationCompleted);
            }
            this.InvokeAsync("getAlunosD", new object[0], this.getAlunosDOperationCompleted, userState);
        }
        
        private void OngetAlunosDOperationCompleted(object arg) {
            if ((this.getAlunosDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAlunosDCompleted(this, new getAlunosDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCadeirasD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cadeira[] getCadeirasD() {
            object[] results = this.Invoke("getCadeirasD", new object[0]);
            return ((Cadeira[])(results[0]));
        }
        
        /// <remarks/>
        public void getCadeirasDAsync() {
            this.getCadeirasDAsync(null);
        }
        
        /// <remarks/>
        public void getCadeirasDAsync(object userState) {
            if ((this.getCadeirasDOperationCompleted == null)) {
                this.getCadeirasDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCadeirasDOperationCompleted);
            }
            this.InvokeAsync("getCadeirasD", new object[0], this.getCadeirasDOperationCompleted, userState);
        }
        
        private void OngetCadeirasDOperationCompleted(object arg) {
            if ((this.getCadeirasDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCadeirasDCompleted(this, new getCadeirasDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCadeirasAlunoD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cadeira[] getCadeirasAlunoD(int numero) {
            object[] results = this.Invoke("getCadeirasAlunoD", new object[] {
                        numero});
            return ((Cadeira[])(results[0]));
        }
        
        /// <remarks/>
        public void getCadeirasAlunoDAsync(int numero) {
            this.getCadeirasAlunoDAsync(numero, null);
        }
        
        /// <remarks/>
        public void getCadeirasAlunoDAsync(int numero, object userState) {
            if ((this.getCadeirasAlunoDOperationCompleted == null)) {
                this.getCadeirasAlunoDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCadeirasAlunoDOperationCompleted);
            }
            this.InvokeAsync("getCadeirasAlunoD", new object[] {
                        numero}, this.getCadeirasAlunoDOperationCompleted, userState);
        }
        
        private void OngetCadeirasAlunoDOperationCompleted(object arg) {
            if ((this.getCadeirasAlunoDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCadeirasAlunoDCompleted(this, new getCadeirasAlunoDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addAlunoD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addAlunoD(string nome, int numero) {
            object[] results = this.Invoke("addAlunoD", new object[] {
                        nome,
                        numero});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addAlunoDAsync(string nome, int numero) {
            this.addAlunoDAsync(nome, numero, null);
        }
        
        /// <remarks/>
        public void addAlunoDAsync(string nome, int numero, object userState) {
            if ((this.addAlunoDOperationCompleted == null)) {
                this.addAlunoDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddAlunoDOperationCompleted);
            }
            this.InvokeAsync("addAlunoD", new object[] {
                        nome,
                        numero}, this.addAlunoDOperationCompleted, userState);
        }
        
        private void OnaddAlunoDOperationCompleted(object arg) {
            if ((this.addAlunoDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addAlunoDCompleted(this, new addAlunoDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addCadeiraD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addCadeiraD(string nomeCadeira, int numero, int notaFinal, int numCadeira) {
            object[] results = this.Invoke("addCadeiraD", new object[] {
                        nomeCadeira,
                        numero,
                        notaFinal,
                        numCadeira});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addCadeiraDAsync(string nomeCadeira, int numero, int notaFinal, int numCadeira) {
            this.addCadeiraDAsync(nomeCadeira, numero, notaFinal, numCadeira, null);
        }
        
        /// <remarks/>
        public void addCadeiraDAsync(string nomeCadeira, int numero, int notaFinal, int numCadeira, object userState) {
            if ((this.addCadeiraDOperationCompleted == null)) {
                this.addCadeiraDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddCadeiraDOperationCompleted);
            }
            this.InvokeAsync("addCadeiraD", new object[] {
                        nomeCadeira,
                        numero,
                        notaFinal,
                        numCadeira}, this.addCadeiraDOperationCompleted, userState);
        }
        
        private void OnaddCadeiraDOperationCompleted(object arg) {
            if ((this.addCadeiraDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addCadeiraDCompleted(this, new addCadeiraDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Main {
        
        private int numeroAlunoField;
        
        private string nomeField;
        
        /// <remarks/>
        public int NumeroAluno {
            get {
                return this.numeroAlunoField;
            }
            set {
                this.numeroAlunoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cadeira {
        
        private int codCadeiraField;
        
        private int numeroAlunoField;
        
        private string nomeCadeiraField;
        
        private int notaFinalField;
        
        /// <remarks/>
        public int CodCadeira {
            get {
                return this.codCadeiraField;
            }
            set {
                this.codCadeiraField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroAluno {
            get {
                return this.numeroAlunoField;
            }
            set {
                this.numeroAlunoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeCadeira {
            get {
                return this.nomeCadeiraField;
            }
            set {
                this.nomeCadeiraField = value;
            }
        }
        
        /// <remarks/>
        public int NotaFinal {
            get {
                return this.notaFinalField;
            }
            set {
                this.notaFinalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getAlunosLCompletedEventHandler(object sender, getAlunosLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAlunosLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAlunosLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Main[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Main[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getCadeirasLCompletedEventHandler(object sender, getCadeirasLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCadeirasLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCadeirasLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cadeira[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cadeira[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getCadeirasAlunoLCompletedEventHandler(object sender, getCadeirasAlunoLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCadeirasAlunoLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCadeirasAlunoLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cadeira[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cadeira[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void addAlunoLCompletedEventHandler(object sender, addAlunoLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addAlunoLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addAlunoLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void addCadeiraLCompletedEventHandler(object sender, addCadeiraLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addCadeiraLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addCadeiraLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getAlunosMCompletedEventHandler(object sender, getAlunosMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAlunosMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAlunosMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Main[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Main[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getCadeirasMCompletedEventHandler(object sender, getCadeirasMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCadeirasMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCadeirasMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cadeira[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cadeira[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getCadeirasAlunoMCompletedEventHandler(object sender, getCadeirasAlunoMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCadeirasAlunoMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCadeirasAlunoMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cadeira[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cadeira[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void addAlunoMCompletedEventHandler(object sender, addAlunoMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addAlunoMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addAlunoMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void addCadeiraMCompletedEventHandler(object sender, addCadeiraMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addCadeiraMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addCadeiraMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getAlunosDCompletedEventHandler(object sender, getAlunosDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAlunosDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAlunosDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Main[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Main[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getCadeirasDCompletedEventHandler(object sender, getCadeirasDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCadeirasDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCadeirasDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cadeira[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cadeira[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getCadeirasAlunoDCompletedEventHandler(object sender, getCadeirasAlunoDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCadeirasAlunoDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCadeirasAlunoDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cadeira[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cadeira[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void addAlunoDCompletedEventHandler(object sender, addAlunoDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addAlunoDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addAlunoDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void addCadeiraDCompletedEventHandler(object sender, addCadeiraDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addCadeiraDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addCadeiraDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591