//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClientApplication.UserService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserServiceSoap", Namespace="http://tempuri.org/")]
    public partial class UserService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getCadeirasOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCadeirasMOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserMOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCadeirasDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserService() {
            this.Url = global::ClientApplication.Properties.Settings.Default.ClientApplication_UserService_UserService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getCadeirasCompletedEventHandler getCadeirasCompleted;
        
        /// <remarks/>
        public event getUserCompletedEventHandler getUserCompleted;
        
        /// <remarks/>
        public event getCadeirasMCompletedEventHandler getCadeirasMCompleted;
        
        /// <remarks/>
        public event getUserMCompletedEventHandler getUserMCompleted;
        
        /// <remarks/>
        public event getCadeirasDCompletedEventHandler getCadeirasDCompleted;
        
        /// <remarks/>
        public event getUserDCompletedEventHandler getUserDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCadeiras", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cadeira[] getCadeiras(int num) {
            object[] results = this.Invoke("getCadeiras", new object[] {
                        num});
            return ((Cadeira[])(results[0]));
        }
        
        /// <remarks/>
        public void getCadeirasAsync(int num) {
            this.getCadeirasAsync(num, null);
        }
        
        /// <remarks/>
        public void getCadeirasAsync(int num, object userState) {
            if ((this.getCadeirasOperationCompleted == null)) {
                this.getCadeirasOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCadeirasOperationCompleted);
            }
            this.InvokeAsync("getCadeiras", new object[] {
                        num}, this.getCadeirasOperationCompleted, userState);
        }
        
        private void OngetCadeirasOperationCompleted(object arg) {
            if ((this.getCadeirasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCadeirasCompleted(this, new getCadeirasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Main getUser(string nome) {
            object[] results = this.Invoke("getUser", new object[] {
                        nome});
            return ((Main)(results[0]));
        }
        
        /// <remarks/>
        public void getUserAsync(string nome) {
            this.getUserAsync(nome, null);
        }
        
        /// <remarks/>
        public void getUserAsync(string nome, object userState) {
            if ((this.getUserOperationCompleted == null)) {
                this.getUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserOperationCompleted);
            }
            this.InvokeAsync("getUser", new object[] {
                        nome}, this.getUserOperationCompleted, userState);
        }
        
        private void OngetUserOperationCompleted(object arg) {
            if ((this.getUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserCompleted(this, new getUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCadeirasM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cadeira[] getCadeirasM(int num) {
            object[] results = this.Invoke("getCadeirasM", new object[] {
                        num});
            return ((Cadeira[])(results[0]));
        }
        
        /// <remarks/>
        public void getCadeirasMAsync(int num) {
            this.getCadeirasMAsync(num, null);
        }
        
        /// <remarks/>
        public void getCadeirasMAsync(int num, object userState) {
            if ((this.getCadeirasMOperationCompleted == null)) {
                this.getCadeirasMOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCadeirasMOperationCompleted);
            }
            this.InvokeAsync("getCadeirasM", new object[] {
                        num}, this.getCadeirasMOperationCompleted, userState);
        }
        
        private void OngetCadeirasMOperationCompleted(object arg) {
            if ((this.getCadeirasMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCadeirasMCompleted(this, new getCadeirasMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Main getUserM(string nome) {
            object[] results = this.Invoke("getUserM", new object[] {
                        nome});
            return ((Main)(results[0]));
        }
        
        /// <remarks/>
        public void getUserMAsync(string nome) {
            this.getUserMAsync(nome, null);
        }
        
        /// <remarks/>
        public void getUserMAsync(string nome, object userState) {
            if ((this.getUserMOperationCompleted == null)) {
                this.getUserMOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserMOperationCompleted);
            }
            this.InvokeAsync("getUserM", new object[] {
                        nome}, this.getUserMOperationCompleted, userState);
        }
        
        private void OngetUserMOperationCompleted(object arg) {
            if ((this.getUserMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserMCompleted(this, new getUserMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCadeirasD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cadeira[] getCadeirasD(int num) {
            object[] results = this.Invoke("getCadeirasD", new object[] {
                        num});
            return ((Cadeira[])(results[0]));
        }
        
        /// <remarks/>
        public void getCadeirasDAsync(int num) {
            this.getCadeirasDAsync(num, null);
        }
        
        /// <remarks/>
        public void getCadeirasDAsync(int num, object userState) {
            if ((this.getCadeirasDOperationCompleted == null)) {
                this.getCadeirasDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCadeirasDOperationCompleted);
            }
            this.InvokeAsync("getCadeirasD", new object[] {
                        num}, this.getCadeirasDOperationCompleted, userState);
        }
        
        private void OngetCadeirasDOperationCompleted(object arg) {
            if ((this.getCadeirasDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCadeirasDCompleted(this, new getCadeirasDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Main getUserD(string nome) {
            object[] results = this.Invoke("getUserD", new object[] {
                        nome});
            return ((Main)(results[0]));
        }
        
        /// <remarks/>
        public void getUserDAsync(string nome) {
            this.getUserDAsync(nome, null);
        }
        
        /// <remarks/>
        public void getUserDAsync(string nome, object userState) {
            if ((this.getUserDOperationCompleted == null)) {
                this.getUserDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserDOperationCompleted);
            }
            this.InvokeAsync("getUserD", new object[] {
                        nome}, this.getUserDOperationCompleted, userState);
        }
        
        private void OngetUserDOperationCompleted(object arg) {
            if ((this.getUserDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserDCompleted(this, new getUserDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cadeira {
        
        private int codCadeiraField;
        
        private int numeroAlunoField;
        
        private string nomeCadeiraField;
        
        private int notaFinalField;
        
        /// <remarks/>
        public int CodCadeira {
            get {
                return this.codCadeiraField;
            }
            set {
                this.codCadeiraField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroAluno {
            get {
                return this.numeroAlunoField;
            }
            set {
                this.numeroAlunoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeCadeira {
            get {
                return this.nomeCadeiraField;
            }
            set {
                this.nomeCadeiraField = value;
            }
        }
        
        /// <remarks/>
        public int NotaFinal {
            get {
                return this.notaFinalField;
            }
            set {
                this.notaFinalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Main {
        
        private int numeroAlunoField;
        
        private string nomeField;
        
        /// <remarks/>
        public int NumeroAluno {
            get {
                return this.numeroAlunoField;
            }
            set {
                this.numeroAlunoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getCadeirasCompletedEventHandler(object sender, getCadeirasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCadeirasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCadeirasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cadeira[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cadeira[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getUserCompletedEventHandler(object sender, getUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Main Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Main)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getCadeirasMCompletedEventHandler(object sender, getCadeirasMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCadeirasMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCadeirasMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cadeira[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cadeira[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getUserMCompletedEventHandler(object sender, getUserMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Main Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Main)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getCadeirasDCompletedEventHandler(object sender, getCadeirasDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCadeirasDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCadeirasDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cadeira[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cadeira[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getUserDCompletedEventHandler(object sender, getUserDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Main Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Main)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591