//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cadeira
    {
        public int CodCadeira { get; set; }
        public int NumeroAluno { get; set; }
        public string NomeCadeira { get; set; }
        public int NotaFinal { get; set; }
    }
}
